#!/bin/bash
# gdal doesn't have make uninstall so this removes files in /usr/local

rm -dvi /usr/local/bin/testepsg
rm -dvi /usr/local/bin/ogrtindex
rm -dvi /usr/local/bin/ogrlineref
rm -dvi /usr/local/bin/ogrinfo
rm -dvi /usr/local/bin/ogr2ogr
rm -dvi /usr/local/bin/nearblack
rm -dvi /usr/local/bin/gnmmanage
rm -dvi /usr/local/bin/gnmanalyse
rm -dvi /usr/local/bin/gdalwarp
rm -dvi /usr/local/bin/gdaltransform
rm -dvi /usr/local/bin/gdaltindex
rm -dvi /usr/local/bin/gdalsrsinfo
rm -dvi /usr/local/bin/gdalserver
rm -dvi /usr/local/bin/gdalmanage
rm -dvi /usr/local/bin/gdallocationinfo
rm -dvi /usr/local/bin/gdalinfo
rm -dvi /usr/local/bin/gdalenhance
rm -dvi /usr/local/bin/gdaldem
rm -dvi /usr/local/bin/gdalbuildvrt
rm -dvi /usr/local/bin/gdaladdo
rm -dvi /usr/local/bin/gdal_translate
rm -dvi /usr/local/bin/gdal_rasterize
rm -dvi /usr/local/bin/gdal_grid
rm -dvi /usr/local/bin/gdal_contour
rm -dvi /usr/local/bin/gdal-config
rm -dvi /usr/local/etc/bash_completion.d/gdal-bash-completion.sh
rm -dvi /usr/local/etc/bash_completion.d/
rm -dvi /usr/local/include/vrtdataset.h
rm -dvi /usr/local/include/rawdataset.h
rm -dvi /usr/local/include/ogrsf_frmts.h
rm -dvi /usr/local/include/ogr_srs_api.h
rm -dvi /usr/local/include/ogr_spatialref.h
rm -dvi /usr/local/include/ogr_p.h
rm -dvi /usr/local/include/ogr_geometry.h
rm -dvi /usr/local/include/ogr_geocoding.h
rm -dvi /usr/local/include/ogr_featurestyle.h
rm -dvi /usr/local/include/ogr_feature.h
rm -dvi /usr/local/include/ogr_core.h
rm -dvi /usr/local/include/ogr_api.h
rm -dvi /usr/local/include/memdataset.h
rm -dvi /usr/local/include/gnmgraph.h
rm -dvi /usr/local/include/gnm_api.h
rm -dvi /usr/local/include/gnm.h
rm -dvi /usr/local/include/gdalwarper.h
rm -dvi /usr/local/include/gdalpansharpen.h
rm -dvi /usr/local/include/gdaljp2metadata.h
rm -dvi /usr/local/include/gdaljp2abstractdataset.h
rm -dvi /usr/local/include/gdalgrid_priv.h
rm -dvi /usr/local/include/gdalgrid.h
rm -dvi /usr/local/include/gdalgeorefpamdataset.h
rm -dvi /usr/local/include/gdal_vrt.h
rm -dvi /usr/local/include/gdal_version.h
rm -dvi /usr/local/include/gdal_utils.h
rm -dvi /usr/local/include/gdal_simplesurf.h
rm -dvi /usr/local/include/gdal_rat.h
rm -dvi /usr/local/include/gdal_proxy.h
rm -dvi /usr/local/include/gdal_priv.h
rm -dvi /usr/local/include/gdal_pam.h
rm -dvi /usr/local/include/gdal_mdreader.h
rm -dvi /usr/local/include/gdal_frmts.h
rm -dvi /usr/local/include/gdal_csv.h
rm -dvi /usr/local/include/gdal_alg_priv.h
rm -dvi /usr/local/include/gdal_alg.h
rm -dvi /usr/local/include/gdal.h
rm -dvi /usr/local/include/cplkeywordparser.h
rm -dvi /usr/local/include/cpl_vsi_virtual.h
rm -dvi /usr/local/include/cpl_vsi_error.h
rm -dvi /usr/local/include/cpl_vsi.h
rm -dvi /usr/local/include/cpl_virtualmem.h
rm -dvi /usr/local/include/cpl_time.h
rm -dvi /usr/local/include/cpl_string.h
rm -dvi /usr/local/include/cpl_spawn.h
rm -dvi /usr/local/include/cpl_quad_tree.h
rm -dvi /usr/local/include/cpl_progress.h
rm -dvi /usr/local/include/cpl_port.h
rm -dvi /usr/local/include/cpl_odbc.h
rm -dvi /usr/local/include/cpl_multiproc.h
rm -dvi /usr/local/include/cpl_minizip_zip.h
rm -dvi /usr/local/include/cpl_minizip_unzip.h
rm -dvi /usr/local/include/cpl_minizip_ioapi.h
rm -dvi /usr/local/include/cpl_minixml.h
rm -dvi /usr/local/include/cpl_list.h
rm -dvi /usr/local/include/cpl_json.h
rm -dvi /usr/local/include/cpl_http.h
rm -dvi /usr/local/include/cpl_hash_set.h
rm -dvi /usr/local/include/cpl_error.h
rm -dvi /usr/local/include/cpl_csv.h
rm -dvi /usr/local/include/cpl_conv.h
rm -dvi /usr/local/include/cpl_config_extras.h
rm -dvi /usr/local/include/cpl_config.h
rm -dvi /usr/local/include/cpl_auto_close.h
rm -dvi /usr/local/include/cpl_atomic_ops.h
rm -dvi /usr/local/lib/pkgconfig/gdal.pc
rm -dvi /usr/local/lib/pkgconfig/
rm -dvi /usr/local/lib/gdalplugins/
rm -dvi /usr/local/lib/libgdal.so.20.5.4
rm -dvi /usr/local/lib/libgdal.so.20
rm -dvi /usr/local/lib/libgdal.so
rm -dvi /usr/local/lib/libgdal.la
rm -dvi /usr/local/lib/libgdal.a
rm -dvi /usr/local/share/gdal/vertcs.override.csv
rm -dvi /usr/local/share/gdal/vertcs.csv
rm -dvi /usr/local/share/gdal/vdv452.xsd
rm -dvi /usr/local/share/gdal/vdv452.xml
rm -dvi /usr/local/share/gdal/unit_of_measure.csv
rm -dvi /usr/local/share/gdal/trailer.dxf
rm -dvi /usr/local/share/gdal/stateplane.csv
rm -dvi /usr/local/share/gdal/seed_3d.dgn
rm -dvi /usr/local/share/gdal/seed_2d.dgn
rm -dvi /usr/local/share/gdal/s57objectclasses.csv
rm -dvi /usr/local/share/gdal/s57expectedinput.csv
rm -dvi /usr/local/share/gdal/s57attributes.csv
rm -dvi /usr/local/share/gdal/s57agencies.csv
rm -dvi /usr/local/share/gdal/ruian_vf_v1.gfs
rm -dvi /usr/local/share/gdal/ruian_vf_st_v1.gfs
rm -dvi /usr/local/share/gdal/ruian_vf_st_uvoh_v1.gfs
rm -dvi /usr/local/share/gdal/ruian_vf_ob_v1.gfs
rm -dvi /usr/local/share/gdal/projop_wparm.csv
rm -dvi /usr/local/share/gdal/prime_meridian.csv
rm -dvi /usr/local/share/gdal/plscenesconf.json
rm -dvi /usr/local/share/gdal/pds4_template.xml
rm -dvi /usr/local/share/gdal/pcs.override.csv
rm -dvi /usr/local/share/gdal/pcs.csv
rm -dvi /usr/local/share/gdal/pci_ellips.txt
rm -dvi /usr/local/share/gdal/pci_datum.txt
rm -dvi /usr/local/share/gdal/ozi_ellips.csv
rm -dvi /usr/local/share/gdal/ozi_datum.csv
rm -dvi /usr/local/share/gdal/osmconf.ini
rm -dvi /usr/local/share/gdal/ogrvrt.xsd
rm -dvi /usr/local/share/gdal/nitf_spec.xsd
rm -dvi /usr/local/share/gdal/nitf_spec.xml
rm -dvi /usr/local/share/gdal/netcdf_config.xsd
rm -dvi /usr/local/share/gdal/jpfgdgml_WStrL.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_WStrA.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_WL.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_WA.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_SBBdry.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_SBArea.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_SBAPt.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_RvrMgtBdry.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_RdSgmtA.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_RdMgtBdry.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_RdEdg.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_RdCompt.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_RdArea.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_RdASL.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_RailCL.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_LeveeEdge.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_GCP.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_ElevPt.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_Cstline.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_CommPt.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_CommBdry.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_Cntr.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_BldL.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_BldA.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_AdmPt.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_AdmBdry.gfs
rm -dvi /usr/local/share/gdal/jpfgdgml_AdmArea.gfs
rm -dvi /usr/local/share/gdal/inspire_cp_CadastralZoning.gfs
rm -dvi /usr/local/share/gdal/inspire_cp_CadastralParcel.gfs
rm -dvi /usr/local/share/gdal/inspire_cp_CadastralBoundary.gfs
rm -dvi /usr/local/share/gdal/inspire_cp_BasicPropertyUnit.gfs
rm -dvi /usr/local/share/gdal/header.dxf
rm -dvi /usr/local/share/gdal/gt_ellips.csv
rm -dvi /usr/local/share/gdal/gt_datum.csv
rm -dvi /usr/local/share/gdal/gmlasconf.xsd
rm -dvi /usr/local/share/gdal/gmlasconf.xml
rm -dvi /usr/local/share/gdal/gml_registry.xml
rm -dvi /usr/local/share/gdal/geoccs.csv
rm -dvi /usr/local/share/gdal/gdalvrt.xsd
rm -dvi /usr/local/share/gdal/gdalicon.png
rm -dvi /usr/local/share/gdal/gdal_datum.csv
rm -dvi /usr/local/share/gdal/gcs.override.csv
rm -dvi /usr/local/share/gdal/gcs.csv
rm -dvi /usr/local/share/gdal/esri_extra.wkt
rm -dvi /usr/local/share/gdal/esri_epsg.wkt
rm -dvi /usr/local/share/gdal/esri_Wisconsin_extra.wkt
rm -dvi /usr/local/share/gdal/esri_StatePlane_extra.wkt
rm -dvi /usr/local/share/gdal/epsg.wkt
rm -dvi /usr/local/share/gdal/ellipsoid.csv
rm -dvi /usr/local/share/gdal/eedaconf.json
rm -dvi /usr/local/share/gdal/ecw_cs.wkt
rm -dvi /usr/local/share/gdal/default.rsc
rm -dvi /usr/local/share/gdal/datum_shift.csv
rm -dvi /usr/local/share/gdal/cubewerx_extra.wkt
rm -dvi /usr/local/share/gdal/coordinate_axis.csv
rm -dvi /usr/local/share/gdal/compdcs.csv
rm -dvi /usr/local/share/gdal/bag_template.xml
rm -dvi /usr/local/share/gdal/LICENSE.TXT
rm -dvi /usr/local/share/gdal/GDALLogoGS.svg
rm -dvi /usr/local/share/gdal/GDALLogoColor.svg
rm -dvi /usr/local/share/gdal/GDALLogoBW.svg
rm -dvi /usr/local/share/gdal/
